// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MonPetitSurf.Models;

public partial class Spots
{
    public int Id { get; set; }

    public string SpotName { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public string Department { get; set; }

    public virtual ICollection<SpotsGetUtilities> SpotsGetUtilities { get; set; } = new List<SpotsGetUtilities>();

    public virtual ICollection<UsersRegisterSpots> UsersRegisterSpots { get; set; } = new List<UsersRegisterSpots>();
}