// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MonPetitSurf.Models;

public partial class SpotsGetUtilities
{
    public int SpotId { get; set; }

    public int UtilityId { get; set; }

    public virtual Spots Spot { get; set; }

    public virtual Utilities Utility { get; set; }
}