// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MonPetitSurf.Models;

public partial class UsersRegisterSpots
{
    public int UserId { get; set; }

    public int SpotId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Spots Spot { get; set; }

    public virtual Users User { get; set; }
}