// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MonPetitSurf.Models;

public partial class Users
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual ICollection<UsersRegisterSpots> UsersRegisterSpots { get; set; } = new List<UsersRegisterSpots>();
}