// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MonPetitSurf.Models;

public partial class Utilities
{
    public int Id { get; set; }

    public string Title { get; set; }

    public virtual ICollection<SpotsGetUtilities> SpotsGetUtilities { get; set; } = new List<SpotsGetUtilities>();
}